// Route inventory (§93). Every core route is checked on every viewport project.
export const ROUTES: { path: string; expect: string }[] = [
  { path: "/", expect: "Forschungsleitstand" },
  { path: "/tracks", expect: "Research tracks" },
  { path: "/tracks/authority", expect: "Authority-Preserving" },
  { path: "/tracks/provenance", expect: "Causal Provenance" },
  { path: "/tracks/cognitive-provenance", expect: "Cognitive Provenance" },
  { path: "/tracks/measurement", expect: "Measurement Governance" },
  { path: "/tracks/memory", expect: "Memory, State" },
  { path: "/tracks/trajectory", expect: "Trajectory Safety" },
  { path: "/claims", expect: "Claim-Register" },
  { path: "/claims/LOGOS-CP-001", expect: "ReasoningContent" },
  { path: "/experiments", expect: "Experimente" },
  { path: "/experiments/EXP-CPA-RERUN", expect: "EXP-CPA-RERUN" },
  { path: "/invariants", expect: "Invarianten" },
  { path: "/counterexamples", expect: "Counterexample registry" },
  { path: "/negative-results", expect: "Negative results" },
  { path: "/falsification", expect: "What could prove us wrong" },
  { path: "/replication", expect: "Replication layer" },
  { path: "/publications", expect: "paper series" },
  { path: "/publications/PAPER-3", expect: "Reasoning Content Is Not Reasoning Provenance" },
  { path: "/prior-art/matrix", expect: "Literatur-Matrix" }, { path: "/evals", expect: "Agenten-Qualität" }, { path: "/publications/PAPER-2/draft", expect: "Paper-Entwurf" }, { path: "/prior-art", expect: "Prior-art registry" },
  { path: "/open-questions", expect: "Research questions queue" },
  { path: "/research", expect: "Deep-research queue" },
  { path: "/timeline", expect: "Scientific timeline" },
  { path: "/reproducibility", expect: "Reproducibility" },
  { path: "/p7", expect: "Functional Evidence Boundary" },
  { path: "/theses", expect: "Thesen-Arbeit" }, { path: "/board", expect: "Thesen-Board" },
  { path: "/work-orders", expect: "Work Orders" }, { path: "/queue", expect: "Warteschlange" }, { path: "/runs", expect: "Live-Läufe" }, { path: "/decisions", expect: "Entscheidungen" },
  { path: "/inbox", expect: "Eingang" }, { path: "/radar", expect: "Radar" }, { path: "/notes", expect: "Notizbuch" }, { path: "/observability", expect: "Beobachtung" }, { path: "/insights", expect: "Was wissen wir jetzt?" }, { path: "/registry", expect: "Registerpflege" }, { path: "/traces", expect: "Traces" }, { path: "/measurements", expect: "Messlauf" }, { path: "/benchmarks", expect: "Benchmark-Labor" },
  { path: "/progress", expect: "Monatsfortschritt" }, { path: "/statistics", expect: "Statistik" }, { path: "/system/health", expect: "Systemzustand" }, { path: "/system/qa", expect: "Playwright-QA" }, { path: "/reports", expect: "Monatsbericht" }, { path: "/evidence-debt", expect: "Evidenzschuld" }, { path: "/system/claude", expect: "Claude-Auth" }, { path: "/system/workers", expect: "Worker" }, { path: "/system/quotas", expect: "Quoten" },
  { path: "/system/governance", expect: "Governance" },
];
