// Route inventory (§93). Every core route is checked on every viewport project.
export const ROUTES: { path: string; expect: string }[] = [
  { path: "/", expect: "LOGOS-1" },
  { path: "/tracks", expect: "Research tracks" },
  { path: "/tracks/authority", expect: "Authority-Preserving" },
  { path: "/tracks/provenance", expect: "Causal Provenance" },
  { path: "/tracks/cognitive-provenance", expect: "Cognitive Provenance" },
  { path: "/tracks/measurement", expect: "Measurement Governance" },
  { path: "/tracks/memory", expect: "Memory, State" },
  { path: "/tracks/trajectory", expect: "Trajectory Safety" },
  { path: "/claims", expect: "Claim registry" },
  { path: "/claims/LOGOS-CP-001", expect: "ReasoningContent" },
  { path: "/experiments", expect: "Experiment registry" },
  { path: "/experiments/EXP-CPA-RERUN", expect: "EXP-CPA-RERUN" },
  { path: "/invariants", expect: "Invariant registry" },
  { path: "/counterexamples", expect: "Counterexample registry" },
  { path: "/negative-results", expect: "Negative results" },
  { path: "/falsification", expect: "What could prove us wrong" },
  { path: "/replication", expect: "Replication layer" },
  { path: "/publications", expect: "paper series" },
  { path: "/publications/PAPER-3", expect: "Reasoning Content Is Not Reasoning Provenance" },
  { path: "/prior-art", expect: "Prior-art registry" },
  { path: "/open-questions", expect: "Research questions queue" },
  { path: "/research", expect: "Deep-research queue" },
  { path: "/timeline", expect: "Scientific timeline" },
  { path: "/reproducibility", expect: "Reproducibility" },
  { path: "/p7", expect: "Functional Evidence Boundary" },
  { path: "/theses", expect: "Work on theses" },
];
