export const de = {
  app_title: "LOGOS-1", app_subtitle: "Forschungsbetriebssystem",
  area_operate: "Betrieb", area_analyze: "Analyse", area_knowledge: "Wissen", area_publish: "Publizieren", area_system: "System",
  nav_command_center: "Kommandozentrale", nav_theses: "Thesen", nav_board: "Thesen-Board", nav_work_orders: "Work Orders", nav_queue: "Warteschlange", nav_runs: "Live-Läufe", nav_decisions: "Entscheidungen", nav_inbox: "Eingang", nav_radar: "Radar",
  nav_traces: "Traces", nav_experiments: "Experimente", nav_benchmarks: "Benchmarks", nav_progress: "Monatsfortschritt", nav_statistics: "Statistik", nav_negative: "Negativergebnisse", nav_counterexamples: "Gegenbeispiele", nav_replication: "Replikation",
  nav_claims: "Claims", nav_invariants: "Invarianten", nav_graph: "Was könnte uns widerlegen?", nav_prior_art: "Prior Art", nav_open_questions: "Offene Fragen", nav_timeline: "Zeitleiste", nav_reproducibility: "Reproduzierbarkeit", nav_p7: "P7-Grenze", nav_tracks: "Tracks",
  nav_publications: "Publikationen", nav_exports: "Export", nav_artifacts: "Artefakte", nav_research: "Deep Research",
  nav_mlflow: "MLflow", nav_workers: "Worker", nav_claude: "Claude-Auth", nav_quotas: "Quoten", nav_governance: "Governance", nav_qa: "Playwright-QA", nav_health: "Systemzustand", nav_settings: "Einstellungen",
  nav_collapse: "Einklappen", nav_expand: "Ausklappen", nav_open: "Navigation",
  claims_title: "Claim-Register", claims_subtitle: "Status der Hypothese ≠ Evidenzstärke; beides wird gezeigt. Status kommen nur aus dem Register, nie aus Freitext.",
  footer_rule: "Jede Aussage verweist auf einen Repository-Record. Status ≠ Evidenzstärke. Nichts hier ist eine Aussage über phänomenales Bewusstsein (P7).",
  not_extracted: "nicht extrahiert", scope: "Geltungsbereich", copy: "kopieren", copied: "kopiert", inspector_empty: "Zeile auswählen, um Details zu sehen.", inspector_title: "Details",
  search: "Suchen …", columns: "Spalten", rows: "Zeilen", phase_note: "Diese Ansicht wird in Phase {n} des Research-OS-Auftrags gebaut.", spec_section: "Spezifikation",
  ros_records_only: "Kontrollebene nicht erreichbar (Lab-Postgres) — Ansicht im records-only-Modus.", ros_theses_title: "Thesen-Arbeit", ros_theses_subtitle: "Auswahl (ACTIVE-THESES.json, Founder) und Lebenszyklus je These (ros_theses). Agenten dürfen bis PREREG_DRAFT arbeiten; PREREG_FROZEN, APPROVE und READY_TO_RUN sind Founder-Gates.", ros_create_thesis: "These anlegen", ros_created: "angelegt", ros_lifecycle: "Lebenszyklus", ros_events: "Ereignisse", ros_available: "Mögliche Übergänge", ros_actor: "Handelnder", ros_founder_gate: "Founder-Gate", ros_reason: "Begründung", ros_apply: "Anwenden", ros_agent_ceiling: "Agenten-Grenze", ros_no_theses: "Noch keine These in der Kontrollebene. Auf /theses eine These aus einem ausgewählten Claim anlegen.", ros_work_orders_title: "Work Orders", ros_work_orders_subtitle: "Entwürfe aus Thesen; Pflichtfelder Frage, Scope, Hypothese, Falsifikationskriterium, Metriken, Governance, Caps. Nur der Founder gibt frei (APPROVE); Ausführung erst mit Executor (Phase 3).", ros_dag: "Abhängigkeits-DAG", ros_ready: "bereit", ros_blocked: "wartet auf", ros_new_wo: "Work Order (DRAFT) anlegen", ros_decisions_title: "Entscheidungen", ros_decisions_subtitle: "Gate-Center: WAITING · APPROVED · REJECTED · DEFERRED · SUPERSEDED. Was passiert bei Freigabe / Ablehnung steht auf jeder Karte; blockierte Objekte sind verlinkt.", ros_open_from_closures: "Offene Governance-Fragen aus Closures (Repository)", ros_approve: "Freigeben", ros_reject: "Ablehnen", ros_defer: "Zurückstellen", ros_if_approved: "Bei Freigabe", ros_if_rejected: "Bei Ablehnung", ros_blocks: "Blockiert", ros_queue_title: "Warteschlange", ros_queue_subtitle: "ros_jobs (Postgres, SKIP LOCKED, Idempotenzschlüssel). Deterministische Jobs starten als queued, Claude-Jobs als waiting_governance. Kein Executor in Phase 2 — Jobs werden aufgezeichnet, nie ausgeführt.", ros_pause: "Pause", ros_resume: "Fortsetzen", ros_stop: "Stopp", ros_retry: "Erneut", ros_enqueue: "Job einreihen", ros_board_title: "Thesen-Board", ros_board_subtitle: "Spalten = Zustände des Lebenszyklus. Verschieben ruft dieselbe Übergangsfunktion wie die Buttons — illegale Übergänge und Founder-Gates werden abgelehnt.", ros_notes: "Founder-Notizen", ros_note_placeholder: "Notiz für den nächsten Agenten-Job …", ros_add_note: "Notiz speichern", ros_decision_flag: "Entscheidung nötig",
  ros_runs_title: "Live-Läufe", ros_runs_subtitle: "Jeder Lauf = ein Job des Host-Executors (Claude, Founder-Start) oder des deterministischen Workers. Ereignisstrom append-only (ros_run_events); Start / Pause / Stop wirken auf den Job.", ros_console: "Run-Konsole", ros_start: "Start", ros_gate_preview: "Gate prüfen", ros_agent_job: "Agenten-Job einreihen", ros_agent_job_hint: "Agent arbeitet eine Stufe (bis PREREG_DRAFT); Start bleibt Founder-Klick; ein Claude-Aufruf pro Job.", ros_live: "live", ros_finished: "beendet", ros_no_events: "Noch keine Ereignisse.", ros_claude_title: "Claude-Auth", ros_claude_subtitle: "Zero-Inference-Nachweis: `claude --version` und `claude auth status --json` (nur Klassenfelder: loggedIn, authMethod, apiProvider, subscriptionType; keine Identifier). Gültig 24 h; ohne frischen Nachweis kein Start.", ros_preflight: "Preflight ausführen", ros_attestation: "Auth-Nachweis", ros_contamination: "Kontamination (nur Präsenz)", ros_quota: "Quota", ros_quota_reset: "Quota-Zustand zurücksetzen (Founder)", ros_workers_title: "Worker", ros_workers_subtitle: "Heartbeats des Host-Executors (Claude-Jobs) und der deterministischen Worker (Docker `ros-worker`). Cap für parallele Claude-Sitzungen = governed cap (1); Änderung nur per Founder-Amendment.", ros_quotas_title: "Quoten", ros_quotas_subtitle: "Claude-Max-Quota ist die einzige Inferenzquelle. USAGE_LIMIT_REACHED → STOP, warten auf Reset; kein PAYG-, Provider- oder Modell-Fallback.", ros_caps: "Caps (governed)", ros_running: "laufend", ros_alive: "aktiv", ros_dead: "kein Heartbeat",
};
export type Dict = { [K in keyof typeof de]: string };
