import type { Dict } from "./de";
export const en: Dict = {
  app_title: "LOGOS-1", app_subtitle: "Research operating system",
  area_operate: "Operate", area_analyze: "Analyze", area_knowledge: "Knowledge", area_publish: "Publish", area_system: "System",
  nav_command_center: "Command Center", nav_theses: "Theses", nav_board: "Thesis board", nav_work_orders: "Work Orders", nav_queue: "Run Queue", nav_runs: "Live Runs", nav_decisions: "Decisions / Gates", nav_inbox: "Research Inbox", nav_radar: "Radar Inbox",
  nav_traces: "Traces", nav_experiments: "Experiments", nav_benchmarks: "Benchmarks", nav_progress: "Monthly Progress", nav_statistics: "Statistics", nav_negative: "Negative Results", nav_counterexamples: "Counterexamples", nav_replication: "Replication",
  nav_claims: "Claims", nav_invariants: "Invariants", nav_graph: "What could prove us wrong?", nav_prior_art: "Prior Art", nav_open_questions: "Open Questions", nav_timeline: "Timeline", nav_reproducibility: "Reproducibility", nav_p7: "P7 Boundary", nav_tracks: "Tracks",
  nav_publications: "Publications", nav_exports: "Export / Research Briefs", nav_artifacts: "Artifacts", nav_research: "Deep Research",
  nav_mlflow: "MLflow", nav_workers: "Workers", nav_claude: "Claude Auth Status", nav_quotas: "Quotas", nav_governance: "Governance", nav_qa: "Playwright QA", nav_health: "System Health", nav_settings: "Settings",
  nav_collapse: "Collapse", nav_expand: "Expand", nav_open: "Navigation",
  claims_title: "Claim registry", claims_subtitle: "Status of hypothesis ≠ strength of evidence; both are shown. Statuses come only from the registry, never from free text.",
  footer_rule: "Every statement links to a repository record. Status ≠ strength of evidence. Nothing here is a claim about phenomenal consciousness (P7).",
  not_extracted: "not extracted", scope: "Scope", copy: "copy", copied: "copied", inspector_empty: "Select a row to see details.", inspector_title: "Details",
  search: "Search …", columns: "Columns", rows: "rows", phase_note: "This view is built in phase {n} of the Research OS order.", spec_section: "Specification",
  ros_records_only: "Control plane unreachable (lab Postgres) — records-only view.", ros_theses_title: "Thesis work", ros_theses_subtitle: "Selection (ACTIVE-THESES.json, founder) and lifecycle per thesis (ros_theses). Agents may work up to PREREG_DRAFT; PREREG_FROZEN, APPROVE and READY_TO_RUN are founder gates.", ros_create_thesis: "Create thesis", ros_created: "created", ros_lifecycle: "Lifecycle", ros_events: "Events", ros_available: "Available transitions", ros_actor: "Actor", ros_founder_gate: "Founder gate", ros_reason: "Reason", ros_apply: "Apply", ros_agent_ceiling: "Agent ceiling", ros_no_theses: "No thesis in the control plane yet. Create one on /theses from a selected claim.", ros_work_orders_title: "Work orders", ros_work_orders_subtitle: "Drafts from theses; mandatory fields question, scope, hypothesis, falsification criterion, metrics, governance, caps. Only the founder approves; execution needs the executor (Phase 3).", ros_dag: "Dependency DAG", ros_ready: "ready", ros_blocked: "waiting on", ros_new_wo: "Create work order (DRAFT)", ros_decisions_title: "Decisions", ros_decisions_subtitle: "Gate center: WAITING · APPROVED · REJECTED · DEFERRED · SUPERSEDED. Each card states what approval / rejection does; blocked objects are linked.", ros_open_from_closures: "Open governance questions from closures (repository)", ros_approve: "Approve", ros_reject: "Reject", ros_defer: "Defer", ros_if_approved: "If approved", ros_if_rejected: "If rejected", ros_blocks: "Blocks", ros_queue_title: "Queue", ros_queue_subtitle: "ros_jobs (Postgres, SKIP LOCKED, idempotency key). Deterministic jobs start queued, Claude jobs waiting_governance. No executor in Phase 2 — jobs are recorded, never run.", ros_pause: "Pause", ros_resume: "Resume", ros_stop: "Stop", ros_retry: "Retry", ros_enqueue: "Enqueue job", ros_board_title: "Thesis board", ros_board_subtitle: "Columns = lifecycle states. Moving a card calls the same transition function as the buttons — illegal transitions and founder gates are rejected.", ros_notes: "Founder notes", ros_note_placeholder: "Note for the next agent job …", ros_add_note: "Save note", ros_decision_flag: "decision needed",
  ros_runs_title: "Live runs", ros_runs_subtitle: "Each run = one job of the host executor (Claude, founder Start) or the deterministic worker. Append-only event stream (ros_run_events); Start / Pause / Stop act on the job.", ros_console: "Run console", ros_start: "Start", ros_gate_preview: "Check gate", ros_agent_job: "Enqueue agent job", ros_agent_job_hint: "The agent advances one stage (up to PREREG_DRAFT); Start stays a founder click; one Claude invocation per job.", ros_live: "live", ros_finished: "finished", ros_no_events: "No events yet.", ros_claude_title: "Claude auth", ros_claude_subtitle: "Zero-inference evidence: `claude --version` and `claude auth status --json` (class fields only: loggedIn, authMethod, apiProvider, subscriptionType; no identifiers). Valid 24 h; no Start without fresh evidence.", ros_preflight: "Run preflight", ros_attestation: "Auth evidence", ros_contamination: "Contamination (presence only)", ros_quota: "Quota", ros_quota_reset: "Reset quota state (founder)", ros_workers_title: "Workers", ros_workers_subtitle: "Heartbeats of the host executor (Claude jobs) and the deterministic workers (Docker `ros-worker`). Parallel Claude sessions cap = governed cap (1); changes only via founder amendment.", ros_quotas_title: "Quotas", ros_quotas_subtitle: "Claude Max quota is the only inference source. USAGE_LIMIT_REACHED → STOP, wait for the reset; no PAYG, provider or model fallback.", ros_caps: "Caps (governed)", ros_running: "running", ros_alive: "alive", ros_dead: "no heartbeat",
  ros_traces_title: "Traces", ros_traces_subtitle: "Every run is mirrored into MLflow (experiment logos-research-os), OTel (one span per phase) and Langfuse (Claude generation); the event stream stays canonical. Telemetry failures degrade, never block.", ros_waterfall: "Waterfall", ros_invocation: "Claude invocation", ros_links: "Links", ros_rescore: "Re-score (no inference)", ros_rescore_hint: "Reads claude_result.json from MLflow and re-parses against ros-agent-result/1 — no model call.", ros_mlflow_open: "Open in MLflow", ros_degraded: "Telemetry degraded", ros_artifacts: "Artifacts",
};
